language: node_js
node_js:
  - "0.12.7"
notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
branches:
  only:
    - master
    - stable
before_script:
  - npm install -g gulp
script: gulp